version = 3.7.3
runner.dialect = scala212source3
align.preset = more
maxColumn = 120
newlines.topLevelStatementBlankLines = [
  {
    blanks {
      before = 1,
      after = 1,
      afterAll = 0,
      beforeAll = 0
    }
  }
]
fileOverride {
  "glob:**/load/src/test/scala/**" {
     runner.dialect = scala213
  }
}
