rules = [
ProcedureSyntax,
OrganizeImports,
RedundantSyntax,
RemoveUnused
]
OrganizeImports.removeUnused = true
OrganizeImports.expandRelative = true
OrganizeImports.groups = [
  "java.*"
  "javax.*"
  "scala.*"
  "microsoft"
  "*"
  "code.*"
]
// OrganizeImports.removeUnsed and RemoveUnused.imports are mututally exclusive see https://scalacenter.github.io/scalafix/docs/rules/OrganizeImports.html
RemoveUnused.imports = false  
RemoveUnused.privates = false
RemoveUnused.locals = false
RemoveUnused.patternvars = true
RemoveUnused.params = true
